version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: “arn:aws:ecs:ap-south-1:957779811736:task-definition/Fronted-Task:2",
        LoadBalancerInfo:
          ContainerName: 'Fronted-Container'
          ContainerPort: 3000
        PlatformVersion: 'LATEST'
